FROM hubimage/nvidia-tritonserver:24.08-py3

RUN pip install --no-cache-dir "numpy<2"

RUN pip install --no-cache-dir \
    torch \
    transformers \
    sentence-transformers \
    protobuf \
    accelerate