name: "orchestrator"
backend: "python"
max_batch_size: 0  

input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ 1 ]           
  }
]
output [
  {
    name: "response"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]